[package]
name = "ray-marching"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
vulkano = "0.27.1"
vulkano-shaders = "0.27.1"
vulkano-win = "0.27.1"
winit = "0.25.0"
